version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Directorio donde está el archivo requirements.txt o pyproject.toml
    schedule:
      interval: "daily" # Puede ser daily, weekly, o monthly
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10

